SELECT name FROM world WHERE continent = 'Europe';
SELECT DISTINCT continent FROM world;
SELECT name FROM world WHERE name LIKE 'F%';
SELECT name FROM world where name LIKE '%z%';
SELECT name FROM world WHERE population < 1000000;
SELECT name, population FROM world WHERE continent = 'Europe';
SELECT name, population FROM world WHERE name IN ('France', 'Germany', 'Italy');
SELECT population FROM world WHERE name = 'France';
SELECT name, population, area FROM world WHERE population > 1e8 OR area > 3e6 ORDER BY name;
SELECT name, population, area FROM world WHERE continent = 'Europe' AND (population > 50e6 or area > 500000);
SELECT name, population, area FROM world WHERE (population > 100e6 AND area < 3e6) OR (population < 100e6 AND area > 3e6);
SELECT name FROM world WHERE name = capital ORDER BY name;
SELECT name, capital FROM world WHERE LENGTH(name) = LENGTH(capital) AND name != capital;
SELECT name, population FROM world WHERE population = (SELECT min(population) from world);
SELECT name, population FROM world WHERE population IS NOT NULL ORDER BY population DESC LIMIT 5;
SELECT name, population, area FROM world ORDER BY name LIMIT 1 OFFSET 99;
SELECT name, population FROM (SELECT * FROM world WHERE area IS NOT NULL ORDER BY area DESC LIMIT 20) AS M1 WHERE population IS NOT NULL ORDER BY population DESC LIMIT 10;
SELECT name, (SELECT population/area WHERE area != 0) AS density FROM world WHERE continent = 'Asia' ORDER BY name;
SELECT name, CASE WHEN (density > 100) THEN 'yes' ELSE 'no' END AS dense FROM (SELECT name, population/area AS density FROM world WHERE (area IS NOT NULL AND area != 0 AND continent = 'Asia') ORDER BY name);
SELECT COUNT(*) FROM world;
SELECT SUM(population) FROM world;
SELECT continent, COUNT(*) AS count FROM world GROUP BY continent ORDER BY continent;
SELECT continent, SUM(population), SUM(area) FROM world GROUP BY continent ORDER BY continent;
SELECT continent, SUM(population) AS total FROM world GROUP BY continent HAVING SUM(population) > 1e8 ORDER BY continent;
SELECT continent, COUNT(*) FROM world WHERE population > 1e6 GROUP BY continent ORDER BY continent;
SELECT AVG(population) AS average FROM world;
SELECT continent, ROUND(SUM(population)/SUM(area)) AS total, ROUND(AVG(CASE WHEN (area IS NOT NULL AND area != 0) THEN population/area END)) AS average, ROUND(SUM(CASE WHEN (area IS NOT NULL AND area != 0) THEN population/area END)/COUNT(*)) AS fake_average FROM world GROUP BY continent;
SELECT SUBSTR(name, 1, 1) AS alpha, SUM(population) FROM world GROUP BY alpha ORDER BY alpha;
SELECT continent, (SELECT name FROM world WHERE continent = w.continent AND area = (SELECT MAX(area) FROM world WHERE continent = w.continent)) AS largest, (SELECT name FROM world WHERE continent = w.continent AND population = (SELECT MAX(population) FROM world WHERE continent = w.continent)) AS most_populous FROM world AS w GROUP BY continent ORDER BY continent;
SELECT continent, (SELECT COUNT(*) FROM world WHERE population > (SELECT population FROM world WHERE area = (SELECT MAX(area) FROM world WHERE continent = w.continent) AND continent = w.continent) AND continent = w.continent) AS sum FROM world AS w GROUP BY continent ORDER BY continent;
